name: AU

on:
  schedule:
    - cron: '0 3 * * 1'   # щопонеділка о 03:00 UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: windows-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4
      - name: Debug files
        shell: pwsh
        run: |
             pwd
             dir
      - name: Install AU
        shell: pwsh
        run: Install-Module au -Scope CurrentUser -Force

      - name: Run AU
        shell: pwsh
        run: ./update.ps1

      - name: Install package locally
        shell: pwsh
        run: choco install httpdownloader -y -s .

      - name: Run verifier
        shell: pwsh
        run: ./tools/verifier.ps1

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "AU: update package" || echo "No changes"
          git push
